export enum PROVINCE_ERROR_CODE {
  NOT_EXISTS = 'PROVINCE_NOT_EXISTS',
  ALREADY_EXISTS = 'PROVINCE_ALREADY_EXISTS',
}

export enum DISTRICT_ERROR_CODE {
  NOT_EXISTS = 'DISTRICT_NOT_EXISTS',
  ALREADY_EXISTS = 'DISTRICT_ALREADY_EXISTS',
}

export enum WARD_ERROR_CODE {
  NOT_EXISTS = 'WARD_NOT_EXISTS',
  ALREADY_EXISTS = 'WARD_ALREADY_EXISTS',
}

export enum PROVINCE_WEBSITE_ERROR_CODE {
  NOT_EXISTS = 'PROVINCE_NOT_EXISTS',
  ALREADY_EXISTS = 'PROVINCE_ALREADY_EXISTS',
}

export enum DISTRICT_WEBSITE_ERROR_CODE {
  NOT_EXISTS = 'DISTRICT_NOT_EXISTS',
  ALREADY_EXISTS = 'DISTRICT_ALREADY_EXISTS',
}

export enum WARD_WEBSITE_ERROR_CODE {
  NOT_EXISTS = 'WARD_NOT_EXISTS',
  ALREADY_EXISTS = 'WARD_ALREADY_EXISTS',
}

export enum ADDRESS_BOOK_ERROR_CODE {
  NOT_EXISTS = 'ADDRESS_BOOK_NOT_EXISTS',
  ALREADY_EXISTS = 'ADDRESS_BOOK_ALREADY_EXISTS',
}
