export enum PROVINCE_ERROR_CODE {
  NOT_EXISTS = 'PROVINCE_NOT_EXISTS',
  ALREADY_EXISTS = 'PROVINCE_ALREADY_EXISTS',
}

export enum DISTRICT_ERROR_CODE {
  NOT_EXISTS = 'DISTRICT_NOT_EXISTS',
  ALREADY_EXISTS = 'DISTRICT_ALREADY_EXISTS',
}

export enum PROVINCE_WEBSITE_ERROR_CODE {
  NOT_EXISTS = 'PROVINCE_NOT_EXISTS',
  ALREADY_EXISTS = 'PROVINCE_ALREADY_EXISTS',
}

export enum DISTRICT_WEBSITE_ERROR_CODE {
  NOT_EXISTS = 'DISTRICT_NOT_EXISTS',
  ALREADY_EXISTS = 'DISTRICT_ALREADY_EXISTS',
}
