export enum PROVINCE_ERROR_CODE {
  PROVINCE_NOT_EXISTS = 'PROVINCE_NOT_EXISTS',
  PROVINCE_ALREADY_EXISTS = 'PROVINCE_ALREADY_EXISTS',
}

export enum PROVINCE_WEBSITE_ERROR_CODE {
  PROVINCE_NOT_EXISTS = 'PROVINCE_NOT_EXISTS',
  PROVINCE_ALREADY_EXISTS = 'PROVINCE_ALREADY_EXISTS',
}
