export const LOCATION_ERROR_CODE = {
  PROVINCE_NOT_EXISTS: 'PROVINCE_NOT_EXISTS',
  PROVINCE_ALREADY_EXISTS: 'PROVINCE_ALREADY_EXISTS',
  DISTRICT_NOT_EXISTS: 'DISTRICT_NOT_EXISTS',
  DISTRICT_ALREADY_EXISTS: 'DISTRICT_ALREADY_EXISTS',
  WARD_NOT_EXISTS: 'WARD_NOT_EXISTS',
  WARD_ALREADY_EXISTS: 'WARD_ALREADY_EXISTS',
};
