export enum MEM_CACHING_KEY_ENUM {
  CLOUDFLARE_VARIANTS = 'CLOUDFLARE_VARIANTS',
  WEBSITE_CONFIG_LIST = 'PUBLIC_WEBSITE_CONFIG_LIST',
  WEBSITE_CONFIG = 'PUBLIC_WEBSITE_CONFIG',
  CATEGORY_LIST = 'PUBLIC_CATEGORY_LIST',
  CATEGORY = 'PUBLIC_CATEGORY',
  CATEGORY_ROOTS = 'PUBLIC_CATEGORY_ROOTS',
  POST = 'PUBLIC_POST',
  POST_LIST = 'PUBLIC_POST_LIST',
  POST_RANDOM = 'PUBLIC_POST_RANDOM',
}
