export enum CATEGORY_ERROR_CODE {
  CATEGORY_NOT_EXISTS = 'CATEGORY_NOT_EXISTS',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_PROPERTY_NOT_EXISTS = 'CATEGORY_PROPERTY_NOT_EXISTS',
  CATEGORY_PROPERTY_ALREADY_EXISTS = 'CATEGORY_PROPERTY_ALREADY_EXISTS',
}
